name: Composite Post Action Demo

on:
  push:
    branches:
      - master

jobs:
  demo:
    name: Composite Post Action Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Demo
        uses: ./.github/actions/cache

      - name: Echo
        run: echo "Hello world"
